// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3it4ABWPFL6-SOf334FaL_F6VmNjhijo',
    appId: '1:185416275971:web:10db9862511eba69411636',
    messagingSenderId: '185416275971',
    projectId: 'shopping-app-589c4',
    authDomain: 'shopping-app-589c4.firebaseapp.com',
    databaseURL: 'https://shopping-app-589c4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-589c4.appspot.com',
    measurementId: 'G-Z5CZ98M1X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqLlEO7GIr1B0x9Bj8C4L8X-0vE6yVYg',
    appId: '1:185416275971:android:38cbe8d587aa4816411636',
    messagingSenderId: '185416275971',
    projectId: 'shopping-app-589c4',
    databaseURL: 'https://shopping-app-589c4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-589c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYDsKkFd036tzGzL_8aQ-AxQxzhsmm_4A',
    appId: '1:185416275971:ios:42c2ba8c00561b1b411636',
    messagingSenderId: '185416275971',
    projectId: 'shopping-app-589c4',
    databaseURL: 'https://shopping-app-589c4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-589c4.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYDsKkFd036tzGzL_8aQ-AxQxzhsmm_4A',
    appId: '1:185416275971:ios:bda6a7f877063116411636',
    messagingSenderId: '185416275971',
    projectId: 'shopping-app-589c4',
    databaseURL: 'https://shopping-app-589c4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-589c4.appspot.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
